# basic options
title: AZAHROU
author: aazahrou
email: a@azahrou.com
description: Stay Tune, Digital Marketer WS is Running!!
twitter_username: azahrou
github_username:  aazahrou

# Build settings
markdown: kramdown
theme: minima
